### ISSUE TITLE
Apply IntranetGeoIP before anonymizing IP address

### ISSUE THREAD

**Issue by cam2** [ThaDafinser/Piwik-IntranetGeoIP#11]
I have noticed that if I turn on anonymizing of IP addresses, the IntranetGeoIP plugin uses the anonymized IP to return GeoIP information.  I'm trying to do a fairly detailed layout of internal networks, so I get inaccurate information.  If I turn off IP anonymize, it works as expected.  Is there a way to do the IntranetGeoIP resolution before anonymizing the IP?

**Comment by ThaDafinser** [comment]
@cam2 good question,but i think that is not possible as a plugin.
Or at least it should not be possible .....otherwise the anonymisation is nothing worth?! //cc @mattab

The plugin uses this event:
https://developer.piwik.org/api-reference/events#trackernewvisitorinformation

And then this field which like written in the docs can be anonymized:
`location_ip: the IP address of the computer that the visit was made from. Can be anonymized`
https://developer.piwik.org/guides/persistence-and-the-mysql-backend#visits

**Comment by mattab** [comment]
In the UserCountry plugin the code that fetches the IP to geo locate has the following logic:
```

        $privacyConfig = new PrivacyManagerConfig();

        $ip = $request->getIp();

        if ($privacyConfig->useAnonymizedIpForVisitEnrichment) {
            $ip = $anonymizedIp;
        }


```

Therefore it's OK to use the RAW IP when the user has selected, in privacy settings, ` Also use the Anonymized IP addresses when enriching visits. ` to `NO`

So I think this issue could be reopened :+1:

**Comment by ThaDafinser** [comment]
Fixed with latest release https://github.com/ThaDafinser/Piwik-IntranetGeoIP/releases/tag/2.2.0
