### ISSUE TITLE
How do I update accurate geolocation data for old visitors?

### ISSUE THREAD

**Issue by bigzachattack** [ThaDafinser/Piwik-IntranetGeoIP#9]
I would like to know the location of the visitors before I installed IntranetGeoIP plugin.  I know there is a script that exists for GeoIP.  Will that script work?

Thanks for your work creating this plugin,
Zach

**Comment by ThaDafinser** [comment]
@bigzachattack i currently change the plugin to be a "normal" Geolocation plugin (by extending `Piwik\Plugins\UserCountry\LocationProvider`), so that you can activate/test it under `Settings -> Geolocation` 

The benefit would be that you can use the standard console command, which will work than also with this plugin http://piwik.org/faq/how-to/faq_167/

But the IP will then be already "anonymized" if you have activated it, like reported here https://github.com/ThaDafinser/Piwik-IntranetGeoIP/issues/11
